@url = http://localhost:8080/api/topic

### test get

GET {{url}} HTTP/1.1

### test get by id

GET {{url}}/2 HTTP/1.1

### test post

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "topicId" : 0,
    "name" : "test topic 3"
}

### test put

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "topicId" : 2,
    "name" : "updating test"
}


### test delete

DELETE {{url}}/2 HTTP/1.1